kfp_importances_labels = [
    "interarrival time max incoming",
    "interarrival time max outgoing",
    "interarrival time max in+out",
    "interarrival time avg incoming",
    "interarrival time avg outgoing",
    "interarrival time avg in+out",
    "interarrival time std incoming",
    "interarrival time std outgoing",
    "interarrival time std in+out",
    "interarrival time 75th percentile incoming",
    "interarrival time 75th percentile outgoing",
    "interarrival time 75th percentile in+out",
    "time 25th percentile incoming",
    "time 50th percentile incoming",
    "time 75th percentile incoming",
    "time 100th percentile incoming",
    "time 25th percentile outgoing",
    "time 50th percentile outgoing",
    "time 75th percentile outgoing",
    "time 100th percentile outgoing",
    "time 25th percentile in+out",
    "time 50th percentile in+out",
    "time 75th percentile in+out",
    "time 100th percentile in+out",
    "number of incoming pkts",
    "number of outgoing pkts",
    "number of total pkts",
    "num of incoming pkts in first 30",
    "num of outgoing pkts in first 30",
    "num of incoming pkts in last 30",
    "num of outgoing pkts in last 30",  # up to thirtypkts
    "std of outgoing pkts in chunks of 20",
    "avg of outgoing pkts in chunks of 20",
    "avg num of pkts per second",
    "std of pkts per second",
    "avg order of incoming pkts",
    "avg order of outgoing pkts",
    "std of order of incoming pkts",
    "std of order of outgoing pkts",
    "median of outgoing pkts in chunks of 20",
    "median of pkts per second",
    "min of pkts per second",
    "max of pkts per second",
    "max of outgoing pkts in chunks of 20",
    "percentage of incoming pkts",
    "percentage of outgoing pkts",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "altconcstat",
    "alt_per_sec stat",
    "alt_per_sec stat",
    "alt_per_sec stat",
    "alt_per_sec stat",
    "alt_per_sec stat",
    "alt_per_sec stat",
    "alt_per_sec stat",
    "alt_per_sec stat",
    "alt_per_sec stat",
    "alt_per_sec stat",
    "alt_per_sec stat",
    "alt_per_sec stat",
    "alt_per_sec stat",
    "alt_per_sec stat",
    "alt_per_sec stat",
    "alt_per_sec stat",
    "alt_per_sec stat",
    "alt_per_sec stat",
    "alt_per_sec stat",
    "alt_per_sec stat",
    "alt_per_sec stat",
    "outgoing concentration of packets",
    "sum(alt_per_sec)",
    "sum of all intertime stats",
    "sum of all time percentile stats",
    "total number of pkts",
    "sum of pkt sizes",
    "sum of incoming pkt sizes",
    "sum of outgoing pkt sizes",
    "average pkt size",
    "average incoming pkt size",
    "average outgoing pkt size",
    "variance of all pkt size",
    "variance of incoming pkt sizes",
    "variance of outgoing pkt sizes",
    "std of all pkt size",
    "std of incoming pkt sizes",
    "std of outgoing pkt sizes",
    "max incoming pkt size",
    "max outgoing pkt size",
    "outgoing concentration of packets 0-20",
    "outgoing concentration of packets 20-40",
    "outgoing concentration of packets 40-60",
    "placeholder",
    "placeholder",
    "placeholder",
    "placeholder",
    "placeholder",
    "placeholder",
    "placeholder",
    "placeholder",
    "placeholder",
    "placeholder",
    "placeholder",
    "placeholder",
    "placeholder",
    "placeholder",
    "placeholder",
]


def get_kfp_importances_labels():
    return kfp_importances_labels
